USE codeup_test_db;

INSERT INTO albums (artist_name, album_name, release_date, sales, genre)
VALUES ('Michael Jackson', 'Thriller', 1982, 51.2, 'Pop, Post-Disco, Funk, Rock'),
       ('AC/DC', 'Back in Black', 1980, 30.1, 'Hard Rock'),
       ('Whitney Houston', 'The Bodyguard', 1973, 24.8, 'R&B, Soul, Pop, Soundtrack'),
       ('Pink Floyd', 'The Dark Side of the Moon', 1980, 30.1, 'Progressive Rock'),
       ('Eagles', 'Their Greatest HIts (1971-1975)', 1976, 41.2, 'Country Rock, Soft Rock, Folk Rock'),
       ('Eagles', 'Hotel California', 1976, 31.8, 'Soft Rock'),
       ('Shania Twain', 'Come On Over', 1997, 30.4, 'Country, Pop'),
       ('Fleetwood Mac', 'Rumours', 1977, 29.3, 'Soft Rock'),
       ('Bee Gees', 'Saturday Night Fever', 1977, 22.1, 'Disco'),
       ('Led Zeppelin', 'Led Zeppelin IV', 1971, 30.4, 'Hard Rock, Heavy Metal, Folk Rock'),
       ('Michael Jackson', 'Bad', 1987, 21.1, 'Pop, R&B, Funk, Rock'),
       ('Meat Loaf', 'Bat Out of Hell', 1977, 22, 'Hard Rock, Glam Rock, Progressive Rock'),
       ('Alanis Morissette', 'Jagged Little Pill', 1995, 25.4, 'Alternative Rock'),
       ('Various', 'Dirty Dancing', 1987, 24.1, 'Pop, Rock, R&B'),
       ('Celine Dion', 'Falling Into You', 1996, 21.1, 'Pop, Soft Rock'),
       ('Adele', '21', 2011, 27.1, 'Pop, Soul'),
       ('The Beatles', '1', 2000, 23.2, 'Rock'),
       ('Metallica', 'Metallica', 1991, 22.7, 'Heavy Metal'),
       ('Celine Dion', 'Lets Talk About Love', 1997, 19.5, 'Pop, Soft Rock'),
       ('Bob Marley & The Wailers', 'Legend: The Best Bob Marley & The Wailers', 1984, 22.9, 'Reggae'),
       ('Guns N Roses', 'Appetite for Destruction', 1987, 22.8, 'Hard Rock'),
       ('Bruce Springsteen', 'Born in the USA', 1984, 22, 'Heartland Rock'),
       ('ABBA', 'Gold: Greatest Hits', 1992, 21.6, 'Pop, Disco'),
       ('Dire Straits', 'Brothers in Arms', 1985, 21.1, 'Roots Rock, Blues Rock, Soft Rock'),
       ('Santana', 'Supernatural', 1999, 19.8, 'Latin Rock'),
       ('Madonna', 'The Immaculate Collection', 1990, 19.8, 'Pop, Dance'),
       ('Pink Floyd', 'The Wall', 1979, 18.9, 'Progressive Rock'),
       ('The Beatles', 'Sgt. Peppers Lonely Hearts Club Band', 1967, 18.3, 'Rock'),
       ('Michael Jackson', 'Dangerous', 1991, 17, 'New Jack Swing, R&B, Pop'),
       ('The Beatles', 'Abby Road', 1969, 16.9, 'Rock');